/**
 * Tipe aktivitas untuk activity log dan timeline.
 */
export const ActivityType = {
  ARTICLE_CREATED: "ARTICLE_CREATED",
  ARTICLE_UPDATED: "ARTICLE_UPDATED",
  ARTICLE_SUBMITTED: "ARTICLE_SUBMITTED",
  ARTICLE_APPROVED: "ARTICLE_APPROVED",
  ARTICLE_REJECTED: "ARTICLE_REJECTED",
  ARTICLE_REVISION_REQUESTED: "ARTICLE_REVISION_REQUESTED",
  ARTICLE_PUBLISHED: "ARTICLE_PUBLISHED",
  ARTICLE_PUBLISHED_WP: "ARTICLE_PUBLISHED_WP",
  ARTICLE_ARCHIVED: "ARTICLE_ARCHIVED",
  MEMBER_INVITED: "MEMBER_INVITED",
  MEMBER_JOINED: "MEMBER_JOINED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
  PAYOUT_REQUESTED: "PAYOUT_REQUESTED",
  PAYOUT_APPROVED: "PAYOUT_APPROVED",
  PAYOUT_REJECTED: "PAYOUT_REJECTED",
  PAYOUT_COMPLETED: "PAYOUT_COMPLETED",
  CONNECTION_CREATED: "CONNECTION_CREATED",
  CONNECTION_TESTED: "CONNECTION_TESTED",
  CONNECTION_DELETED: "CONNECTION_DELETED",
  WORKSPACE_UPDATED: "WORKSPACE_UPDATED",
} as const

export type ActivityType = (typeof ActivityType)[keyof typeof ActivityType]
