//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type Article = $ModelResult<$Schema, "Article">;
export type Category = $ModelResult<$Schema, "Category">;
export type ArticleReview = $ModelResult<$Schema, "ArticleReview">;
export type ArticleEvent = $ModelResult<$Schema, "ArticleEvent">;
export type WorkspaceConnection = $ModelResult<$Schema, "WorkspaceConnection">;
export type PayoutRule = $ModelResult<$Schema, "PayoutRule">;
export type UserProfile = $ModelResult<$Schema, "UserProfile">;
export type WorkspacePreference = $ModelResult<$Schema, "WorkspacePreference">;
export type PayoutRequest = $ModelResult<$Schema, "PayoutRequest">;
export type PayoutArticle = $ModelResult<$Schema, "PayoutArticle">;
export type ActivityLog = $ModelResult<$Schema, "ActivityLog">;
export type WpSyncLog = $ModelResult<$Schema, "WpSyncLog">;
export type User = $ModelResult<$Schema, "User">;
export type Session = $ModelResult<$Schema, "Session">;
export type Account = $ModelResult<$Schema, "Account">;
export type Verification = $ModelResult<$Schema, "Verification">;
export type Organization = $ModelResult<$Schema, "Organization">;
export type TwoFactor = $ModelResult<$Schema, "TwoFactor">;
export type Member = $ModelResult<$Schema, "Member">;
export type Invitation = $ModelResult<$Schema, "Invitation">;
