//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
  provider = {
    type: "postgresql"
  } as const;
  models = {
    Article: {
      name: "Article",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        title: {
          name: "title",
          type: "String"
        },
        slug: {
          name: "slug",
          type: "String"
        },
        excerpt: {
          name: "excerpt",
          type: "String",
          optional: true
        },
        content: {
          name: "content",
          type: "String",
          optional: true
        },
        status: {
          name: "status",
          type: "String",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("DRAFT") }] }] as readonly AttributeApplication[],
          default: "DRAFT" as FieldDefault
        },
        wordCount: {
          name: "wordCount",
          type: "Int",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("word_count") }] }] as readonly AttributeApplication[],
          default: 0 as FieldDefault
        },
        honor: {
          name: "honor",
          type: "Int",
          optional: true
        },
        coverImageUrl: {
          name: "coverImageUrl",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("cover_image_url") }] }] as readonly AttributeApplication[]
        },
        categoryId: {
          name: "categoryId",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("category_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "category"
          ] as readonly string[]
        },
        authorId: {
          name: "authorId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("author_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "author"
          ] as readonly string[]
        },
        reviewerId: {
          name: "reviewerId",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("reviewer_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "reviewer"
          ] as readonly string[]
        },
        workspaceId: {
          name: "workspaceId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("workspace_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "workspace"
          ] as readonly string[]
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        updatedAt: {
          name: "updatedAt",
          type: "DateTime",
          updatedAt: true,
          attributes: [{ name: "@updatedAt" }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("updated_at") }] }] as readonly AttributeApplication[]
        },
        publishedAt: {
          name: "publishedAt",
          type: "DateTime",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("published_at") }] }] as readonly AttributeApplication[]
        },
        author: {
          name: "author",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("authoredArticles") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("authorId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "articlesAuthored", name: "authoredArticles", fields: ["authorId"], references: ["id"] }
        },
        reviewer: {
          name: "reviewer",
          type: "User",
          optional: true,
          attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("reviewedArticles") }, { name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("reviewerId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "articlesReviewed", name: "reviewedArticles", fields: ["reviewerId"], references: ["id"] }
        },
        category: {
          name: "category",
          type: "Category",
          optional: true,
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("categoryId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "articles", fields: ["categoryId"], references: ["id"] }
        },
        workspace: {
          name: "workspace",
          type: "Organization",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("workspaceId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "articles", fields: ["workspaceId"], references: ["id"] }
        },
        reviews: {
          name: "reviews",
          type: "ArticleReview",
          array: true,
          relation: { opposite: "article" }
        },
        events: {
          name: "events",
          type: "ArticleEvent",
          array: true,
          relation: { opposite: "article" }
        },
        payoutArticles: {
          name: "payoutArticles",
          type: "PayoutArticle",
          array: true,
          relation: { opposite: "article" }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("articles") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    Category: {
      name: "Category",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        name: {
          name: "name",
          type: "String"
        },
        slug: {
          name: "slug",
          type: "String"
        },
        description: {
          name: "description",
          type: "String",
          optional: true
        },
        color: {
          name: "color",
          type: "String",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("#3b82f6") }] }] as readonly AttributeApplication[],
          default: "#3b82f6" as FieldDefault
        },
        articleCount: {
          name: "articleCount",
          type: "Int",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("article_count") }] }] as readonly AttributeApplication[],
          default: 0 as FieldDefault
        },
        wpCategoryId: {
          name: "wpCategoryId",
          type: "Int",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("wp_category_id") }] }] as readonly AttributeApplication[]
        },
        workspaceId: {
          name: "workspaceId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("workspace_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "workspace"
          ] as readonly string[]
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        workspace: {
          name: "workspace",
          type: "Organization",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("workspaceId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "categories", fields: ["workspaceId"], references: ["id"] }
        },
        articles: {
          name: "articles",
          type: "Article",
          array: true,
          relation: { opposite: "category" }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("categories") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    ArticleReview: {
      name: "ArticleReview",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        articleId: {
          name: "articleId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("article_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "article"
          ] as readonly string[]
        },
        reviewerId: {
          name: "reviewerId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("reviewer_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "reviewer"
          ] as readonly string[]
        },
        score: {
          name: "score",
          type: "Int",
          optional: true
        },
        notes: {
          name: "notes",
          type: "String",
          optional: true
        },
        decision: {
          name: "decision",
          type: "String"
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        article: {
          name: "article",
          type: "Article",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("articleId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "reviews", fields: ["articleId"], references: ["id"] }
        },
        reviewer: {
          name: "reviewer",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("reviewerId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "articleReviews", fields: ["reviewerId"], references: ["id"] }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("article_reviews") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    ArticleEvent: {
      name: "ArticleEvent",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        articleId: {
          name: "articleId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("article_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "article"
          ] as readonly string[]
        },
        userId: {
          name: "userId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("user_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "user"
          ] as readonly string[]
        },
        eventType: {
          name: "eventType",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("event_type") }] }] as readonly AttributeApplication[]
        },
        metadata: {
          name: "metadata",
          type: "String",
          optional: true
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        article: {
          name: "article",
          type: "Article",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("articleId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "events", fields: ["articleId"], references: ["id"] }
        },
        user: {
          name: "user",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "articleEvents", fields: ["userId"], references: ["id"] }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("article_events") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    WorkspaceConnection: {
      name: "WorkspaceConnection",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        workspaceId: {
          name: "workspaceId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("workspace_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "workspace"
          ] as readonly string[]
        },
        type: {
          name: "type",
          type: "String",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("wordpress") }] }] as readonly AttributeApplication[],
          default: "wordpress" as FieldDefault
        },
        config: {
          name: "config",
          type: "String",
          optional: true
        },
        status: {
          name: "status",
          type: "String",
          optional: true,
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("disconnected") }] }] as readonly AttributeApplication[],
          default: "disconnected" as FieldDefault
        },
        lastSyncAt: {
          name: "lastSyncAt",
          type: "DateTime",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("last_sync_at") }] }] as readonly AttributeApplication[]
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        workspace: {
          name: "workspace",
          type: "Organization",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("workspaceId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "connections", fields: ["workspaceId"], references: ["id"] }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("workspace_connections") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    PayoutRule: {
      name: "PayoutRule",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        workspaceId: {
          name: "workspaceId",
          type: "String",
          unique: true,
          attributes: [{ name: "@unique" }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("workspace_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "workspace"
          ] as readonly string[]
        },
        defaultHonor: {
          name: "defaultHonor",
          type: "Int",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(50000) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("default_honor") }] }] as readonly AttributeApplication[],
          default: 50000 as FieldDefault
        },
        minPayout: {
          name: "minPayout",
          type: "Int",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(50000) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("min_payout") }] }] as readonly AttributeApplication[],
          default: 50000 as FieldDefault
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        updatedAt: {
          name: "updatedAt",
          type: "DateTime",
          updatedAt: true,
          attributes: [{ name: "@updatedAt" }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("updated_at") }] }] as readonly AttributeApplication[]
        },
        workspace: {
          name: "workspace",
          type: "Organization",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("workspaceId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "payoutRules", fields: ["workspaceId"], references: ["id"] }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("payout_rules") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" },
        workspaceId: { type: "String" }
      }
    },
    UserProfile: {
      name: "UserProfile",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        userId: {
          name: "userId",
          type: "String",
          unique: true,
          attributes: [{ name: "@unique" }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("user_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "user"
          ] as readonly string[]
        },
        phone: {
          name: "phone",
          type: "String",
          optional: true
        },
        bio: {
          name: "bio",
          type: "String",
          optional: true
        },
        timezone: {
          name: "timezone",
          type: "String",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("Asia/Jakarta") }] }] as readonly AttributeApplication[],
          default: "Asia/Jakarta" as FieldDefault
        },
        locale: {
          name: "locale",
          type: "String",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("id") }] }] as readonly AttributeApplication[],
          default: "id" as FieldDefault
        },
        bankName: {
          name: "bankName",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("bank_name") }] }] as readonly AttributeApplication[]
        },
        bankAccountNumber: {
          name: "bankAccountNumber",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("bank_account_number") }] }] as readonly AttributeApplication[]
        },
        bankAccountName: {
          name: "bankAccountName",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("bank_account_name") }] }] as readonly AttributeApplication[]
        },
        metadata: {
          name: "metadata",
          type: "String",
          optional: true
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        updatedAt: {
          name: "updatedAt",
          type: "DateTime",
          updatedAt: true,
          attributes: [{ name: "@updatedAt" }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("updated_at") }] }] as readonly AttributeApplication[]
        },
        user: {
          name: "user",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
          relation: { opposite: "profile", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("user_profiles") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" },
        userId: { type: "String" }
      }
    },
    WorkspacePreference: {
      name: "WorkspacePreference",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        workspaceId: {
          name: "workspaceId",
          type: "String",
          unique: true,
          attributes: [{ name: "@unique" }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("workspace_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "workspace"
          ] as readonly string[]
        },
        defaultHonor: {
          name: "defaultHonor",
          type: "Int",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(50000) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("default_honor") }] }] as readonly AttributeApplication[],
          default: 50000 as FieldDefault
        },
        minPayout: {
          name: "minPayout",
          type: "Int",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(50000) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("min_payout") }] }] as readonly AttributeApplication[],
          default: 50000 as FieldDefault
        },
        defaultScoreForPublish: {
          name: "defaultScoreForPublish",
          type: "Int",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("default_score_for_publish") }] }] as readonly AttributeApplication[]
        },
        defaultReviewerId: {
          name: "defaultReviewerId",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("default_reviewer_id") }] }] as readonly AttributeApplication[]
        },
        publicJoinEnabled: {
          name: "publicJoinEnabled",
          type: "Boolean",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(true) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("public_join_enabled") }] }] as readonly AttributeApplication[],
          default: true as FieldDefault
        },
        metadata: {
          name: "metadata",
          type: "String",
          optional: true
        },
        logoDark: {
          name: "logoDark",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("logo_dark") }] }] as readonly AttributeApplication[]
        },
        logoLight: {
          name: "logoLight",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("logo_light") }] }] as readonly AttributeApplication[]
        },
        customDomain: {
          name: "customDomain",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("custom_domain") }] }] as readonly AttributeApplication[]
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        updatedAt: {
          name: "updatedAt",
          type: "DateTime",
          updatedAt: true,
          attributes: [{ name: "@updatedAt" }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("updated_at") }] }] as readonly AttributeApplication[]
        },
        workspace: {
          name: "workspace",
          type: "Organization",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("workspaceId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
          relation: { opposite: "preferences", fields: ["workspaceId"], references: ["id"], onDelete: "Cascade" }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("workspace_preferences") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" },
        workspaceId: { type: "String" }
      }
    },
    PayoutRequest: {
      name: "PayoutRequest",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        workspaceId: {
          name: "workspaceId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("workspace_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "workspace"
          ] as readonly string[]
        },
        contributorId: {
          name: "contributorId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("contributor_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "contributor"
          ] as readonly string[]
        },
        totalAmount: {
          name: "totalAmount",
          type: "Int",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("total_amount") }] }] as readonly AttributeApplication[]
        },
        status: {
          name: "status",
          type: "String",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("PENDING") }] }] as readonly AttributeApplication[],
          default: "PENDING" as FieldDefault
        },
        bankName: {
          name: "bankName",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("bank_name") }] }] as readonly AttributeApplication[]
        },
        bankAccountNumber: {
          name: "bankAccountNumber",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("bank_account_number") }] }] as readonly AttributeApplication[]
        },
        bankAccountName: {
          name: "bankAccountName",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("bank_account_name") }] }] as readonly AttributeApplication[]
        },
        reviewNotes: {
          name: "reviewNotes",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("review_notes") }] }] as readonly AttributeApplication[]
        },
        proofUrl: {
          name: "proofUrl",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("proof_url") }] }] as readonly AttributeApplication[]
        },
        requestedAt: {
          name: "requestedAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("requested_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        processedAt: {
          name: "processedAt",
          type: "DateTime",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("processed_at") }] }] as readonly AttributeApplication[]
        },
        completedAt: {
          name: "completedAt",
          type: "DateTime",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("completed_at") }] }] as readonly AttributeApplication[]
        },
        workspace: {
          name: "workspace",
          type: "Organization",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("workspaceId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "payoutRequests", fields: ["workspaceId"], references: ["id"] }
        },
        contributor: {
          name: "contributor",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("contributorId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "payoutRequests", fields: ["contributorId"], references: ["id"] }
        },
        payoutArticles: {
          name: "payoutArticles",
          type: "PayoutArticle",
          array: true,
          relation: { opposite: "payoutRequest" }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("payout_requests") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    PayoutArticle: {
      name: "PayoutArticle",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        payoutRequestId: {
          name: "payoutRequestId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("payout_request_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "payoutRequest"
          ] as readonly string[]
        },
        articleId: {
          name: "articleId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("article_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "article"
          ] as readonly string[]
        },
        amount: {
          name: "amount",
          type: "Int"
        },
        payoutRequest: {
          name: "payoutRequest",
          type: "PayoutRequest",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("payoutRequestId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "payoutArticles", fields: ["payoutRequestId"], references: ["id"] }
        },
        article: {
          name: "article",
          type: "Article",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("articleId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "payoutArticles", fields: ["articleId"], references: ["id"] }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("payout_articles") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    ActivityLog: {
      name: "ActivityLog",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        workspaceId: {
          name: "workspaceId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("workspace_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "workspace"
          ] as readonly string[]
        },
        userId: {
          name: "userId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("user_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "user"
          ] as readonly string[]
        },
        action: {
          name: "action",
          type: "String"
        },
        resourceType: {
          name: "resourceType",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("resource_type") }] }] as readonly AttributeApplication[]
        },
        resourceId: {
          name: "resourceId",
          type: "String",
          optional: true,
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("resource_id") }] }] as readonly AttributeApplication[]
        },
        metadata: {
          name: "metadata",
          type: "String",
          optional: true
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        workspace: {
          name: "workspace",
          type: "Organization",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("workspaceId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "activityLogs", fields: ["workspaceId"], references: ["id"] }
        },
        user: {
          name: "user",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "activityLogs", fields: ["userId"], references: ["id"] }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("activity_logs") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    WpSyncLog: {
      name: "WpSyncLog",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("uuid") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("uuid") as FieldDefault
        },
        workspaceId: {
          name: "workspaceId",
          type: "String",
          attributes: [{ name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("workspace_id") }] }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "workspace"
          ] as readonly string[]
        },
        action: {
          name: "action",
          type: "String"
        },
        status: {
          name: "status",
          type: "String"
        },
        payload: {
          name: "payload",
          type: "String",
          optional: true
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("created_at") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        workspace: {
          name: "workspace",
          type: "Organization",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("workspaceId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
          relation: { opposite: "wpSyncLogs", fields: ["workspaceId"], references: ["id"] }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("wp_sync_logs") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    User: {
      name: "User",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }] as readonly AttributeApplication[]
        },
        name: {
          name: "name",
          type: "String"
        },
        email: {
          name: "email",
          type: "String",
          unique: true,
          attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
        },
        emailVerified: {
          name: "emailVerified",
          type: "Boolean",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }] as readonly AttributeApplication[],
          default: false as FieldDefault
        },
        image: {
          name: "image",
          type: "String",
          optional: true
        },
        twoFactorEnabled: {
          name: "twoFactorEnabled",
          type: "Boolean",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }, { name: "@map", args: [{ name: "name", value: ExpressionUtils.literal("two_factor_enabled") }] }] as readonly AttributeApplication[],
          default: false as FieldDefault
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        updatedAt: {
          name: "updatedAt",
          type: "DateTime",
          updatedAt: true,
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        sessions: {
          name: "sessions",
          type: "Session",
          array: true,
          relation: { opposite: "user" }
        },
        accounts: {
          name: "accounts",
          type: "Account",
          array: true,
          relation: { opposite: "user" }
        },
        members: {
          name: "members",
          type: "Member",
          array: true,
          relation: { opposite: "user" }
        },
        invitations: {
          name: "invitations",
          type: "Invitation",
          array: true,
          relation: { opposite: "user" }
        },
        profile: {
          name: "profile",
          type: "UserProfile",
          optional: true,
          relation: { opposite: "user" }
        },
        twoFactor: {
          name: "twoFactor",
          type: "TwoFactor",
          optional: true,
          relation: { opposite: "user" }
        },
        articlesAuthored: {
          name: "articlesAuthored",
          type: "Article",
          array: true,
          attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("authoredArticles") }] }] as readonly AttributeApplication[],
          relation: { opposite: "author", name: "authoredArticles" }
        },
        articlesReviewed: {
          name: "articlesReviewed",
          type: "Article",
          array: true,
          attributes: [{ name: "@relation", args: [{ name: "name", value: ExpressionUtils.literal("reviewedArticles") }] }] as readonly AttributeApplication[],
          relation: { opposite: "reviewer", name: "reviewedArticles" }
        },
        articleReviews: {
          name: "articleReviews",
          type: "ArticleReview",
          array: true,
          relation: { opposite: "reviewer" }
        },
        articleEvents: {
          name: "articleEvents",
          type: "ArticleEvent",
          array: true,
          relation: { opposite: "user" }
        },
        payoutRequests: {
          name: "payoutRequests",
          type: "PayoutRequest",
          array: true,
          relation: { opposite: "contributor" }
        },
        activityLogs: {
          name: "activityLogs",
          type: "ActivityLog",
          array: true,
          relation: { opposite: "user" }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("user") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" },
        email: { type: "String" }
      }
    },
    Session: {
      name: "Session",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }] as readonly AttributeApplication[]
        },
        expiresAt: {
          name: "expiresAt",
          type: "DateTime"
        },
        token: {
          name: "token",
          type: "String",
          unique: true,
          attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        updatedAt: {
          name: "updatedAt",
          type: "DateTime",
          updatedAt: true,
          attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
        },
        ipAddress: {
          name: "ipAddress",
          type: "String",
          optional: true
        },
        userAgent: {
          name: "userAgent",
          type: "String",
          optional: true
        },
        userId: {
          name: "userId",
          type: "String",
          foreignKeyFor: [
            "user"
          ] as readonly string[]
        },
        user: {
          name: "user",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
          relation: { opposite: "sessions", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
        },
        activeOrganizationId: {
          name: "activeOrganizationId",
          type: "String",
          optional: true
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("session") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" },
        token: { type: "String" }
      }
    },
    Account: {
      name: "Account",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }] as readonly AttributeApplication[]
        },
        accountId: {
          name: "accountId",
          type: "String"
        },
        providerId: {
          name: "providerId",
          type: "String"
        },
        userId: {
          name: "userId",
          type: "String",
          foreignKeyFor: [
            "user"
          ] as readonly string[]
        },
        user: {
          name: "user",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
          relation: { opposite: "accounts", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
        },
        accessToken: {
          name: "accessToken",
          type: "String",
          optional: true
        },
        refreshToken: {
          name: "refreshToken",
          type: "String",
          optional: true
        },
        idToken: {
          name: "idToken",
          type: "String",
          optional: true
        },
        accessTokenExpiresAt: {
          name: "accessTokenExpiresAt",
          type: "DateTime",
          optional: true
        },
        refreshTokenExpiresAt: {
          name: "refreshTokenExpiresAt",
          type: "DateTime",
          optional: true
        },
        scope: {
          name: "scope",
          type: "String",
          optional: true
        },
        password: {
          name: "password",
          type: "String",
          optional: true
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        updatedAt: {
          name: "updatedAt",
          type: "DateTime",
          updatedAt: true,
          attributes: [{ name: "@updatedAt" }] as readonly AttributeApplication[]
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("account") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    Verification: {
      name: "Verification",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }] as readonly AttributeApplication[]
        },
        identifier: {
          name: "identifier",
          type: "String"
        },
        value: {
          name: "value",
          type: "String"
        },
        expiresAt: {
          name: "expiresAt",
          type: "DateTime"
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        updatedAt: {
          name: "updatedAt",
          type: "DateTime",
          updatedAt: true,
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }, { name: "@updatedAt" }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("verification") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    Organization: {
      name: "Organization",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }] as readonly AttributeApplication[]
        },
        name: {
          name: "name",
          type: "String"
        },
        slug: {
          name: "slug",
          type: "String",
          unique: true,
          attributes: [{ name: "@unique" }] as readonly AttributeApplication[]
        },
        logo: {
          name: "logo",
          type: "String",
          optional: true
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime"
        },
        metadata: {
          name: "metadata",
          type: "String",
          optional: true
        },
        members: {
          name: "members",
          type: "Member",
          array: true,
          relation: { opposite: "organization" }
        },
        invitations: {
          name: "invitations",
          type: "Invitation",
          array: true,
          relation: { opposite: "organization" }
        },
        articles: {
          name: "articles",
          type: "Article",
          array: true,
          relation: { opposite: "workspace" }
        },
        categories: {
          name: "categories",
          type: "Category",
          array: true,
          relation: { opposite: "workspace" }
        },
        connections: {
          name: "connections",
          type: "WorkspaceConnection",
          array: true,
          relation: { opposite: "workspace" }
        },
        payoutRules: {
          name: "payoutRules",
          type: "PayoutRule",
          array: true,
          relation: { opposite: "workspace" }
        },
        payoutRequests: {
          name: "payoutRequests",
          type: "PayoutRequest",
          array: true,
          relation: { opposite: "workspace" }
        },
        activityLogs: {
          name: "activityLogs",
          type: "ActivityLog",
          array: true,
          relation: { opposite: "workspace" }
        },
        wpSyncLogs: {
          name: "wpSyncLogs",
          type: "WpSyncLog",
          array: true,
          relation: { opposite: "workspace" }
        },
        preferences: {
          name: "preferences",
          type: "WorkspacePreference",
          optional: true,
          relation: { opposite: "workspace" }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("organization") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" },
        slug: { type: "String" }
      }
    },
    TwoFactor: {
      name: "TwoFactor",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }] as readonly AttributeApplication[]
        },
        userId: {
          name: "userId",
          type: "String",
          unique: true,
          attributes: [{ name: "@unique" }] as readonly AttributeApplication[],
          foreignKeyFor: [
            "user"
          ] as readonly string[]
        },
        secret: {
          name: "secret",
          type: "String"
        },
        backupCodes: {
          name: "backupCodes",
          type: "String",
          optional: true
        },
        verified: {
          name: "verified",
          type: "Boolean",
          optional: true
        },
        failedVerificationCount: {
          name: "failedVerificationCount",
          type: "Int",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(0) }] }] as readonly AttributeApplication[],
          default: 0 as FieldDefault
        },
        lockedUntil: {
          name: "lockedUntil",
          type: "DateTime",
          optional: true
        },
        user: {
          name: "user",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
          relation: { opposite: "twoFactor", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("two_factor") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" },
        userId: { type: "String" }
      }
    },
    Member: {
      name: "Member",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }] as readonly AttributeApplication[]
        },
        organizationId: {
          name: "organizationId",
          type: "String",
          foreignKeyFor: [
            "organization"
          ] as readonly string[]
        },
        organization: {
          name: "organization",
          type: "Organization",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("organizationId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
          relation: { opposite: "members", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
        },
        userId: {
          name: "userId",
          type: "String",
          foreignKeyFor: [
            "user"
          ] as readonly string[]
        },
        user: {
          name: "user",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("userId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
          relation: { opposite: "members", fields: ["userId"], references: ["id"], onDelete: "Cascade" }
        },
        role: {
          name: "role",
          type: "String",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("member") }] }] as readonly AttributeApplication[],
          default: "member" as FieldDefault
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime"
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("member") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    },
    Invitation: {
      name: "Invitation",
      fields: {
        id: {
          name: "id",
          type: "String",
          id: true,
          attributes: [{ name: "@id" }] as readonly AttributeApplication[]
        },
        organizationId: {
          name: "organizationId",
          type: "String",
          foreignKeyFor: [
            "organization"
          ] as readonly string[]
        },
        organization: {
          name: "organization",
          type: "Organization",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("organizationId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
          relation: { opposite: "invitations", fields: ["organizationId"], references: ["id"], onDelete: "Cascade" }
        },
        email: {
          name: "email",
          type: "String"
        },
        role: {
          name: "role",
          type: "String",
          optional: true
        },
        status: {
          name: "status",
          type: "String",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal("pending") }] }] as readonly AttributeApplication[],
          default: "pending" as FieldDefault
        },
        expiresAt: {
          name: "expiresAt",
          type: "DateTime"
        },
        createdAt: {
          name: "createdAt",
          type: "DateTime",
          attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
          default: ExpressionUtils.call("now") as FieldDefault
        },
        inviterId: {
          name: "inviterId",
          type: "String",
          foreignKeyFor: [
            "user"
          ] as readonly string[]
        },
        user: {
          name: "user",
          type: "User",
          attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("inviterId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }, { name: "onDelete", value: ExpressionUtils.literal("Cascade") }] }] as readonly AttributeApplication[],
          relation: { opposite: "invitations", fields: ["inviterId"], references: ["id"], onDelete: "Cascade" }
        }
      },
      attributes: [
        { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("invitation") }] }
      ] as readonly AttributeApplication[],
      idFields: ["id"],
      uniqueFields: {
        id: { type: "String" }
      }
    }
  } as const;
  authType = "User" as const;
  plugins = {};
}
export const schema = new SchemaType();
